In [20]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler, RobustScaler

In [21]:
data = {
    "Age": [18, 19, 20, 21, 25, 17, 35, 32, 30],
    "Weight": [180, 190, 200, 210, 250, 170, 350, 320, 300],
    }
df = pd.DataFrame(data)

In [22]:
scalar = StandardScaler()

scaled_df = scalar.fit_transform(df)

scaled_df = pd.DataFrame(scaled_df, columns=df.columns)
scaled_df

        Age    Weight
0 -0.970454 -0.970454
1 -0.811652 -0.811652
2 -0.652851 -0.652851
3 -0.494049 -0.494049
4  0.141157  0.141157
5 -1.129255 -1.129255
6  1.729172  1.729172
7  1.252768  1.252768
8  0.935165  0.935165

In [25]:
scalar = MinMaxScaler()

scaled_df = scalar.fit_transform(df)

scaled_df = pd.DataFrame(scaled_df, columns=df.columns)
scaled_df

        Age    Weight
0  0.055556  0.055556
1  0.111111  0.111111
2  0.166667  0.166667
3  0.222222  0.222222
4  0.444444  0.444444
5  0.000000  0.000000
6  1.000000  1.000000
7  0.833333  0.833333
8  0.722222  0.722222

In [26]:
scalar = MaxAbsScaler()

scaled_df = scalar.fit_transform(df)

scaled_df = pd.DataFrame(scaled_df, columns=df.columns)
scaled_df.head()

        Age    Weight
0  0.514286  0.514286
1  0.542857  0.542857
2  0.571429  0.571429
3  0.600000  0.600000
4  0.714286  0.714286

In [27]:
scalar = RobustScaler()

scaled_df = scalar.fit_transform(df)

scaled_df = pd.DataFrame(scaled_df, columns=df.columns)
scaled_df.head()

        Age    Weight
0 -0.272727 -0.272727
1 -0.181818 -0.181818
2 -0.090909 -0.090909
3  0.000000  0.000000
4  0.363636  0.363636