In [38]:
# generating synthetic numeric dataset using sklearn

import pandas as pd 
from sklearn.datasets import make_regression, make_classification

In [39]:
X, y = make_regression(n_samples=10000, n_features=10, noise=0.5, n_targets=1, random_state=0)

df = pd.DataFrame(X, columns=[f'features_{i}' for i in range(X.shape[1])])
df['target'] = y
df.head()

,features_0,features_1,features_2,features_3,features_4,features_5,features_6,features_7,features_8,features_9,target
0,-1.138214,-0.422910,-0.964694,0.530064,1.279396,-1.044090,2.797154,-0.327864,0.496472,0.153133,-37.586919
1,0.284315,0.222463,-1.240625,0.016338,0.415401,0.209849,0.381416,0.067492,-0.088376,0.098378,6.465846
2,-0.569802,-1.798101,0.288362,0.718336,0.835645,-0.514267,0.107137,0.480252,-1.513370,0.621687,-286.357049
3,1.075156,-0.322537,-0.538385,-0.554673,-1.316187,0.615463,-0.253289,0.675327,0.482367,-0.354726,20.897325
4,-1.968727,-0.538779,-0.208188,-0.486475,-1.109579,-2.026281,0.752462,-1.298028,-0.052379,1.531367,-283.111452

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, classification_report
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.pipeline import Pipeline

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

models = {
    "KNN": KNeighborsRegressor(n_neighbors=5),
    "LR": LinearRegression(),
    "DT": DecisionTreeRegressor(random_state=0),
    "RFR": RandomForestRegressor(n_estimators=100, random_state=0)
}

for model_name in models:
    model = models[model_name]
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    print(f"------------- Model: {model_name} -------------")
    print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
    print("R^2 Score:", r2_score(y_test, y_pred))
    print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred), end="\n\n")

------------- Model: KNN -------------
Mean Squared Error: 2990.0035646945676
R^2 Score: 0.8853222363429213
Mean Absolute Error: 41.77034483334767

------------- Model: LR -------------
Mean Squared Error: 0.23959163596876368
R^2 Score: 0.9999908107691482
Mean Absolute Error: 0.38748079555715886

------------- Model: DT -------------
Mean Squared Error: 5112.528999853051
R^2 Score: 0.8039154871726717
Mean Absolute Error: 56.09562009341371

------------- Model: RFR -------------
Mean Squared Error: 1721.4103152295365
R^2 Score: 0.9339775083823636
Mean Absolute Error: 31.506981047135422

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

models = {
    "KNN": Pipeline([
        ("scaler", StandardScaler()),
        ("model", KNeighborsRegressor(n_neighbors=5))
        ]),
    "LR": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LinearRegression())
        ]),
    "DT": DecisionTreeRegressor(),
    "RF": RandomForestRegressor()
}

for model_name in models:
    model = models[model_name]
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    print(f"------------- Model: {model_name} -------------")
    print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
    print("R^2 Score:", r2_score(y_test, y_pred))
    print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred), end="\n\n")

------------- Model: KNN -------------
Mean Squared Error: 3010.886800439995
R^2 Score: 0.8845212865375475
Mean Absolute Error: 41.86254108770727

------------- Model: LR -------------
Mean Squared Error: 0.23959163596876124
R^2 Score: 0.9999908107691482
Mean Absolute Error: 0.3874807955571501

------------- Model: DT -------------
Mean Squared Error: 5029.611646552508
R^2 Score: 0.8070956762390488
Mean Absolute Error: 55.66733662966271

------------- Model: RF -------------
Mean Squared Error: 1697.0007704304912
R^2 Score: 0.9349137052626932
Mean Absolute Error: 31.354620962563672

In [43]:
## Classification dataset

X, y = make_classification(n_samples=10000, n_features=10, n_classes=2, n_informative=5, random_state=0)

df = pd.DataFrame(X, columns=[f'features_{i}' for i in range(X.shape[1])])
df['target'] = y
df.head()

,features_0,features_1,features_2,features_3,features_4,features_5,features_6,features_7,features_8,features_9,target
0,-0.348731,-1.084080,0.353742,-1.925695,1.200805,0.894888,-1.254692,-0.905536,0.897054,-0.547971,0
1,-1.114180,0.036282,-0.926790,-0.772499,-2.325781,1.157330,-0.217249,-0.392881,-1.071348,0.728054,1
2,-3.030235,-3.460233,-0.054315,-6.028664,0.026588,1.610505,0.417437,0.711324,1.483904,-0.527376,0
3,1.169632,0.759544,-0.232448,1.762858,-0.091308,-0.213873,-0.019506,0.782132,-0.638585,0.677311,0
4,-2.998352,0.182511,3.945201,-5.111859,-0.193309,3.704356,-0.896828,-0.564727,-0.084847,-3.589312,1

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

models = {
    "KNN": Pipeline([
        ("scaler", StandardScaler()),
        ("model", KNeighborsClassifier(n_neighbors=5))
        ]),
    "LR": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression())
        ]),
    "DT": DecisionTreeClassifier(),
    "RF": RandomForestClassifier()
}

for model_name in models:
    model = models[model_name]
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    print(f"------------- Model: {model_name} -------------")
    print("Accuracy score:", model.score(X_test, y_test))
    # print("Classification Report:\n", classification_report(y_test, y_pred), end="\n\n")

------------- Model: KNN -------------
Accuracy score: 0.8985
------------- Model: LR -------------
Accuracy score: 0.859
------------- Model: DT -------------
Accuracy score: 0.8885
------------- Model: RF -------------
Accuracy score: 0.9265