In [30]:
import pandas as pd
d = pd.read_csv("../employees.csv")

# bool_series = pd.isnull(d["Gender"])
# missing_gender_data = d[pd.isnull(d['Gender'])]
# missing_gender_data.head()
# d.isnull().sum().sort_values(ascending = False)
# d.head(21)

In [34]:
d['Gender'].fillna("No Gender", inplace=True)
d[10:21]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,No Gender,4/22/1995,7:18 PM,64714,4.934,True,Legal

In [36]:
a = pd.read_csv('../employees.csv')
b = a.dropna()

print(len(a)-len(b))

236

In [37]:
data_frame = pd.DataFrame( [['tom', 10], ['nick', '15'], ['juli', 14.8]], columns=['Name', 'Age'])
data_frame

   Name   Age
0   tom    10
1  nick    15
2  juli  14.8