In [37]:
import pandas as pd

In [38]:
path = "C:\\Users\\hamza\\OneDrive\\ML Basics\\datasets\\IPL_Squad_2023_Auction_Dataset.csv"

df = pd.read_csv(path)
df.head()

,Unnamed: 0,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
0,0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans
1,1,Joshua Little,5000000,BOWLER,4.4,528.0,NaN,Gujarat Titans
2,2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans
3,3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans
4,4,Mohit Sharma,5000000,BOWLER,0.5,60.0,NaN,Gujarat Titans

In [39]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)
df.tail()

,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
563,Dhruv Patel,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
564,Jack Prestwidge,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
565,Aditya Sarvate,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
566,Sagar Solanki,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
567,Prenelan Subrayen,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold

In [40]:
df.describe()

       COST IN ₹ (CR.)  Cost IN $ (000)
count       243.000000       243.000000
mean          0.687243        82.469136
std           2.511700       301.404032
min           0.000000         0.000000
25%           0.000000         0.000000
50%           0.000000         0.000000
75%           0.200000        24.000000
max          18.500000      2220.000000